# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ğŸ‘‹  Thanks for opening your first issue here! Please filled out the template with as much details as possible. We appreciate that you took the time to contribute!

  Make sure you read our [contributing guidelines](https://github.com/insarlab/MintPy/blob/master/docs/CONTRIBUTING.md).

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ğŸ’–  Thanks for opening this pull request! Please check out our [contributing guidelines](https://github.com/insarlab/MintPy/blob/master/docs/CONTRIBUTING.md). ğŸ’–

  Keep in mind that all new features should be documented. It helps to write the comments next to the code or below your functions describing **all** arguments, and return types before writing the code. This will help you think about your code design and usually results in better code.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ğŸ‰ ğŸ‰ ğŸ‰  Congrats on merging your first pull request! We here at behaviorbot are proud of you! ğŸ‰ ğŸ‰ ğŸ‰

# It is recommend to include as many gifs and emojis as possible
