# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_prs: false

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=20']
        exclude_types: [image]
        exclude: src/mintpy/data/plate_boundary
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: tests/data/

  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        name: sort imports
        args: ['--multi-line=VERTICAL_HANGING_INDENT',
               '--trailing-comma',
               '--combine-as']

  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.11.0"
    hooks:
      - id: pyupgrade
        name: modernize python
        args: ['--py36-plus']


  ############################################################
  #- repo: https://github.com/psf/black
  #  rev: "22.6.0"
  #  hooks:
  #    - id: black

  #- repo: https://github.com/PyCQA/flake8
  #  rev: "5.0.4"
  #  hooks:
  #    - id: flake8

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: "v0.971"
  #  hooks:
  #    - id: mypy

  #- repo: https://github.com/hadialqattan/pycln
  #  rev: "v2.1.1"
  #  hooks:
  #    - id: pycln

  #- repo: https://github.com/PyCQA/pydocstyle
  #  rev: "6.1.1"
  #  hooks:
  #    - id: pydocstyle
  #      additional_dependencies: [toml]
  #      exclude: test

  #- repo: https://github.com/sirosen/texthooks
  #  rev: "0.3.1"
  #  hooks:
  #    - id: fix-ligatures
  #    - id: fix-smartquotes
