site_name: MintPy
site_url: https://github.com/insarlab/MintPy
site_description: Miami InSAR Time-series software in Python
site_author: Zhang Yunjun, Heresh Fattahi
repo_url: https://github.com/insarlab/MintPy/
google_analytics: ['UA-104225904-1', 'mkdocs.org']

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

markdown_extensions:
    - smarty
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"
    - sane_lists

nav:
    - Home: README.md
    - User Guide:
        - Installation: installation.md
        - Example datasets: demo_dataset.md
        - Example directory structure: dir_structure.md
        - Example template files: templates/README.md
        - Parallel processing with Dask: dask.md
        - Tutorials in Jupyter Notebook: https://github.com/insarlab/MintPy-tutorial
        - Frequently Asked Questions: FAQs.md
    - Output:
        - Google Earth KMZ: google_earth.md
        - HDF-EOS5: hdfeos5.md
        - QGIS: QGIS.md
        - InSAR Explorer: insar_explorer.md
    - API Documentation:
        - Attributes: api/attributes.md
        - Colormaps: api/colormaps.md
        - Coordinates: api/coord.md
        - Data structure: api/data_structure.md
        - Docker: docker.md
        - Documents generation: api/doc_generation.md
        - Module hierarchy: api/module_hierarchy.md
    - About:
        - Contributing: CONTRIBUTING.md
        - Code of conduct: CODE_OF_CONDUCT.md
        - References: references.md
