title: MintPy
description: Miami InSAR time-series software in Python
show_downloads: true
google_analytics: UA-104225904-1
theme: jekyll-theme-cayman
author:
  name: Zhang Yunjun, Heresh Fattahi
  url: https://yunjunz.github.io/
author_email: yunjunz@outlook.com
