# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n mintpy
# enter  environment : conda activate mintpy
# exit   environment : conda deactivate
name: mintpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - cartopy
  - cvxopt
  - dask>=1.0
  - dask-jobqueue>=0.3
  - defusedxml
  - h5py
  - joblib
  - lxml
  - matplotlib
  - numpy
  - pyaps3>=0.3
  - pykml>=0.2
  - pyproj
  - pyresample
  - pysolid
  - rich
  - scikit-image
  - scipy
  # for ISCE, ARIA, FRInGE, HyP3, GMTSAR
  - gdal>=3
